samples: samples.tsv

workflow:
  # whether to plot regions:
  # not recommended for highly fragmented reference assemblies
  do_plot_reg: true

params:
  # maximum threads par task.
  # Applicable to fastqc, cutadapt, bwa mem, samtools merge
  threads: 2
  # additional parameters to cutadapt
  cutadapt:
    # common cutadapt parameters, 
    # per-library additional paramters are set by 
    # "amplification" parameter in samples.tsv
    pe: "--trim-n --minimum-length 20"
    se: "--trim-n --minimum-length 20"
  # additional parameters to Picard
  picard_MarkDuplicates: "-Xmx4G"
  # additional parameters to plotting script
  region:
    # plotting parameters, dims in inches
    plot_ncols: 8
    plot_chrom_height: 2
    plot_chrom_width: 3
