samples: samples.tsv

workflow:
  # whether to plot regions
  # not recommended for highly fragmented reference assemblies
  # unless small number of seqids are specified in chrom_list
  # of samples.tsv file
  do_plot_reg: true

params:
  # maximum threads per bwa mem task
  threads: 2
  # additional parameters ffor cutadapt
  cutadapt:
    # common cutadapt parameters, 
    # per-library additional paramters are set by 
    # "amplification" parameter in samples.tsv
    pe: "--trim-n --minimum-length 20"
    se: "--trim-n --minimum-length 20"
  # additional parameters for Picard
  picard_MarkDuplicates: "-Xmx4G"
  # additional parameters for plotting script
  region:
    # plotting parameters, dimensions in inches
    plot_ncols: 8
    plot_chrom_height: 2
    plot_chrom_width: 3
