samples: samples.tsv

workflow:
  # whether to plot regions:
  # not recommended for highly fragmented reference assemblies
  do_plot_reg: true

params:
  # maximum threads par task: bwa mem, samtools merge
  threads: 1
  cutadapt:
    # common cutadapt parameters, 
    # per-library additional paramters are set by 
    # "amplification" parameter in samples.tsv
    pe: "--trim-n --minimum-length 20"
    se: "--trim-n --minimum-length 20"
  picard:
    # duplicates are removed by default
    MarkDuplicates: "-Xmx4G REMOVE_DUPLICATES=true"
  region:
    # plotting parameters, dims in inches
    plot_ncols: 8
    plot_chrom_height: 2
    plot_chrom_width: 3
